function scr_dg_tutrOLD(act = 0){
	_textarray = [
/*0*/		["YO DYNAMITE! Welcome to Tactical Tutorial.","dialm",true],
/*1*/		["Here you'll be taught all the COOL moves you may or may not know about!","dialm",true],
/*2*/		["Let's start off easy 'n simple.. See that fridge?","dialm",true],
/*3*/		["If you wanna /rKNOCK IT OUT/w, keep pressing keycode@PUNCHkeycode a bunch of times.","dialm",false],
/*4*/		["That's how it's done.","dialm",true],
/*5*/		["Now let's get aerial, jump with keycode@JUMPkeycode and press keycode@PUNCHkeycode to attack mid-air!", "dialm", false],
/*6*/		["You can also perform an UPPERCUT, hold keycode@UPkeycode and press keycode@PUNCHkeycode again.","dialm",false],
/*7*/		["Now try crouching with keycode@CROUCHkeycode and pressing keycode@PUNCHkeycode .","dialm",false],
/*8*/		["GOOD STUFF! Now do the same but keep holding keycode@LEFTkeycode or keycode@RIGHTkeycode .","dialm",false],
/*9*/		["And that's how you do a /ySLIDE KICK!/w","dialm",true],
/*10*/		["(tip: pressing keycode@CROUCHkeycode in the air makes you do a quick drop to the ground, which helps you avoid getting ko'd.)","dialm",true],
/*11*/		["Those were the main moves.","dialm",true],
/*12*/		["Now it's time to learn how to grab.", "dialm", true],
/*13*/		["Get close enough to an enemy and hold keycode@PUNCHkeycode .","dialm",false],
/*14*/		["Then press keycode@PUNCHkeycode again to do a throw!","dialm",false],
/*15*/		["AWESOOOME!", "dialm",true],
/*16*/		["Now, before you venture into Toxic Trenches, you may want to know how to use /yTNT BLAST/w.","dialm",true],
/*17*/		["Every time you land a punch, your /yTNT BLAST meter/w fills up.","dialm",true],
/*18*/		["Once your TNT BLAST points are high enough you can perform a /yMASH ATTACK/w.","dialm",true],
/*19*/		["Press keycode@TNTkeycode now.","dialm",false],
/*20*/		["MAAN. THAT'S THE STUFF, I TELL YA!","dialm",true],
/*21*/		["Now, once that meter FULLY FILLS UP, you can wipe out ALL on-screen enemies.","dialm",true],
/*22*/		["It's full! Hold keycode@TNTkeycode .","dialm",false],
/*23*/		["WOOAH! You're a KILLING MACHINE, DUDE!","dialm",true],
/*24*/		["Great, I'll get a new fridge later.","dh",true],
/*25*/		["That's the spirit, pal.","dialm",true],
/*26*/		["Seems you've got all the moves, I'll catch you later.","dialm",true],
	];
}